name: "Sense"
description: "A Home Assistant Add-on to fetch Sense.com realtime data"
url: "https://github.com/matthewhadley/homeassistant-sense"
version: "0.2.0"
slug: "sense"
init: false
stdin: true
hassio_api: true
homeassistant_api: true
options:
  sense_email: null
  sense_password: null
  interval: 3
schema:
  sense_email: str
  sense_password: str
  interval: int(1,10)?
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "matthewhadley/homeassistant-sense-addon-{arch}"
