name: "Sense"
description: "A Home Assistant Add-on to fetch Sense.com realtime data"
url: "https://github.com/matthewhadley/homeassistant-sense"
version: 0.8.1
slug: sense
init: false
stdin: true
hassio_api: true
homeassistant_api: true
options:
  sense_email: null
  sense_password: null
  interval: 5
  debug: true
schema:
  sense_email: str
  sense_password: str
  interval: int(1,15)?
  debug: bool
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "matthewhadley/homeassistant-sense-addon-{arch}"
