name: Publish
on: push

jobs:
  build:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Version
        id: version
        run: |
          c=$(grep version < sense/config.yaml | grep -o '[0-9\.]*');
          p=$(git show HEAD~1:sense/config.yaml | grep version | grep -o '[0-9\.]*');
          if [[ ! -z "$c" && "$c" != "$p" ]]; then
            echo VERSION="$c" >> $GITHUB_ENV;
          fi
      - name: Echo Version
        run: |
          echo New Version Detected $env.VERSION
      - name: Login to DockerHub
        if: env.VERSION != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        if: env.VERSION != ''
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target sense \
            --docker-hub matthewhadley
